INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(1, 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(2 , 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(3, 2);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(4, 2);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(5, 2);

--

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(6, 6);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(7, 8);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(8, 2);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(9, 2);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(10, 2);

--

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(11, 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(12, 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(13, 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(14, 2);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(15, 2);

--

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(16, 6);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(17, 2);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(18, 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(19, 4);

INSERT INTO ISAD251_STong.TeaRoom_Table
VALUES(20, 2);
